variables: variables.yml
web_server: 
  port: '{? web_port ?}'
  base_url: /
  web_ui: yes
  #run_v2: true

schedules:
  - tasks: ['hdchina', 'wiki','byr_an', 'tjupt', 'hdsky']
    interval:
      minutes: 2
#   - tasks: 'ipt_tvs'
#     schedule:
#       day_of_week: mon
#       hour: 8-10
#       minute: "*/1"

templates:
  use_trs:
    transmission:
      host: '{? trs.host ?}'
      port: '{? trs.port ?}'
      username: '{? trs.usr ?}'
      password: '{? trs.pwd ?}'

    free_space:
      path: '{? movies_path ?}'
      space: 10240
    download: '{? torrent_path ?}'

  use_qbt:
    qbittorrent:
      label: auto
      host: '{? qbt.host ?}'
      port: '{? qbt.port ?}'
      username: '{? qbt.usr ?}'
      password: '{? qbt.pwd ?}'

    free_space:
      path: '{? movies_path ?}'
      space: 10240
    download: '{? torrent_path ?}'

  ##----------------##
  size_movie:
    content_size:
      min: 100
      max: 22480
      strict: no

  ##----------------##
  size_tv:
    content_size:
      min: 500
      max: 11264
      strict: no
  
  ##----------------##
  test_T:
    download: '{? torrent_test_path ?}'

tasks:
  hdchina:
    rss: '{? rss.hdchina ?}'
    accept_all: yes
    exists_movie:
      path: /mnt/data/movies
      allow_different_qualities: better

    template:
      - size_movie
      - use_qbt

    qbittorrent:
      #ratio: 4
      path: '{? movies_path ?}'

  ##----------------##
  wiki:
    rss: '{? rss.wiki ?}'
    template:
      - size_movie
      - use_qbt
    if:
      - "'1080p' in title": reject
      - "'WiKi' in title": accept
    exists_movie:
      path: '{? movies_path ?}'
      allow_different_qualities: better

    qbittorrent:
      #ratio: 2
      path: '{? movies_path ?}'

  ##----------------##
  hdsky:
    rss: '{? rss.hdsky ?}'
    template:
      - size_movie
      - use_qbt
    if:
      - "'Complete' in title": reject
      - "'x264' in title": reject
      - "'iPad' in title": accept
    content_size:
      min: 400
      max: 10240
      strict: no
    qbittorrent:
      #ratio: 2
      path: '{? mp4_path ?}'
      
  ##----------------##
  tjupt:
    rss: '{? rss.tjupt ?}'
    template:
      - size_movie
      - use_qbt
    if:
      #- "'Complete' in title": reject
      - "'NYHD' in title": reject
      - "'-RS' in title": reject
    regexp:
      accept:
        - .*The.Longest.Day.In.Chang'an.*-TJUPT.*
        - .*The.King's.Avatar.2019.*-TJUPT.*
        - .*Grandmaster.of.Demonic.Cultivation.2019.*
        - .*Fights.Break.Sphere.2019.S03.*
      reject:
        - .*-MT.*
        - .*-OurTV.*
        - .*-TPL.*
        - .*4K H265 AAC-MoeCat.*
    qbittorrent:
      #ratio: 2
      path: '{? series_path ?}'

  ##----------------##
  byr_an:
    rss: '{? rss.byr_an ?}'
    template:
      - size_movie
      - use_qbt
    if:
      - "'Complete' in title": reject
      - "'NYHD' in title": reject
      - "'-RS' in title": reject
      - "'HDCTV' in title": reject
      - "'TJUPT' in title": reject
      - "'Great.Journey.Of.Teenagers' in title": accept
      - "'Deadly.Response' in title": accept
    regexp:
      accept:
        - .*INCARNATION.*
        - .*Douro.Mainland.*
        - .*Scissor.Seven*
        - .*Qing.Yu.Nian.2019.*-NM.*

    #exists: '{? series_path ?}'
    qbittorrent:
      #ratio: 2
      path: '{? series_path ?}'

  ##----------------##
  ipt_movies:
    rss: '{? rss.ipt_mvs ?}'
    template:
      - size_movie
      - use_qbt
    quality:
      - 720p bluray
      - 1080p webdl
    regexp:
      accept_excluding:
        - .*-WiKi$
        - .*-HDC$
        - .*remux.*
        - .*-HDS$
        - .*-HDH$
        - .*-CHD$
        - .*-Geek$
        - .*-MT$
        - .*COMPLETE.*
    exists_movie:
      path: '{? movies_path ?}'
      allow_different_qualities: better
    content_size:
      min: 100
      max: 12240
      strict: no
    qbittorrent:
      path: '{? movies_path ?}'
  ##----------------##
  ipt_tvs:
    rss: '{? rss.ipt_tvs ?}'
    template:
      - size_tv
      - use_qbt
    quality:
      - 720p
    regexp:
      accept:
        - game.*of.*Thrones.*s08e06.*720p.*
      reject:
        - .*-MT$
        - .*-HDC$
        - .*hevc.*
        - .*x265.*
        - .*-Mobile$
        - .*HDTV.*
        - .*720p.*-GoT.*

    exists: '{? series_path ?}'
    qbittorrent:
      path: '{? series_path ?}'

  ##----------------##
  got:
    rss: '{? rss.got ?}'
    template:
      - size_tv
      - use_qbt
    quality:
      - 1080p
    regexp:
      accept:
        - .*game.*of.*Thrones.*s08e06.*-GoT.*
    exists: '{? series_path ?}'
    exists_series:
      path: '{? series_path ?}'
      allow_different_qualities: yes
    qbittorrent:
      path: '{? series_path ?}'

  #----------------##
  # for test 
  ttt:
    rss: '{? rss.test_rss ?}'
    #html: '{? rss.test_html ?}'
    template:
      - use_qbt
    regexp:
      accept:
        - .*Chernobyl.S01E03.iNTERNAL.1080p.WEB.H264-MEMENTO.*
        - .*Killing.Eve.*

    #exists: '{? series_path ?}'
    #exists_series: '{? series_path ?}'
    #quality:
      #- 1080p bluray
      #- 720p webdl
